using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CookingApp.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddCanonicalIngredients : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Table already exists in DB — create only if missing
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""CanonicalIngredients"" (
                    ""Id""   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""Name"" text NOT NULL
                );
            ");

            // Column may already exist — add only if missing
            migrationBuilder.Sql(@"
                ALTER TABLE ""Ingredients""
                ADD COLUMN IF NOT EXISTS ""CanonicalIngredientId"" integer
                REFERENCES ""CanonicalIngredients""(""Id"") ON DELETE SET NULL;
            ");

            // Index — create only if missing
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Ingredients_CanonicalIngredientId""
                ON ""Ingredients""(""CanonicalIngredientId"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""Ingredients""
                DROP COLUMN IF EXISTS ""CanonicalIngredientId"";
            ");
        }
    }
}
