// <auto-generated />
using System;
using CookingApp.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CookingApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406000000_AddIngredientSubstitutes")]
    partial class AddIngredientSubstitutes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CookingApp.Core.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "protein",
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            Id = 2,
                            Category = "legume",
                            Name = "Chickpeas"
                        },
                        new
                        {
                            Id = 3,
                            Category = "vegetable",
                            Name = "Potato"
                        },
                        new
                        {
                            Id = 4,
                            Category = "herb",
                            Name = "Holy Basil"
                        },
                        new
                        {
                            Id = 5,
                            Category = "herb",
                            Name = "Thai Basil"
                        },
                        new
                        {
                            Id = 6,
                            Category = "herb",
                            Name = "Italian Basil"
                        },
                        new
                        {
                            Id = 7,
                            Category = "protein",
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 8,
                            Category = "grain",
                            Name = "Breadcrumbs"
                        },
                        new
                        {
                            Id = 9,
                            Category = "vegetable",
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 10,
                            Category = "vegetable",
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 11,
                            Category = "aromatic",
                            Name = "Garlic"
                        },
                        new
                        {
                            Id = 12,
                            Category = "aromatic",
                            Name = "Ginger"
                        },
                        new
                        {
                            Id = 13,
                            Category = "spice",
                            Name = "Cumin"
                        },
                        new
                        {
                            Id = 14,
                            Category = "spice",
                            Name = "Coriander"
                        },
                        new
                        {
                            Id = 15,
                            Category = "spice",
                            Name = "Garam Masala"
                        },
                        new
                        {
                            Id = 16,
                            Category = "condiment",
                            Name = "Fish Sauce"
                        },
                        new
                        {
                            Id = 17,
                            Category = "condiment",
                            Name = "Oyster Sauce"
                        },
                        new
                        {
                            Id = 18,
                            Category = "condiment",
                            Name = "Soy Sauce"
                        },
                        new
                        {
                            Id = 19,
                            Category = "spice",
                            Name = "Red Chili"
                        },
                        new
                        {
                            Id = 20,
                            Category = "grain",
                            Name = "Flour"
                        });
                });

            modelBuilder.Entity("CookingApp.Core.Models.IngredientSubstitute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClosenessRank")
                        .HasColumnType("integer");

                    b.Property<string>("DishImpact")
                        .HasColumnType("text");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OriginalIngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("SubstituteIngredientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OriginalIngredientId");

                    b.HasIndex("SubstituteIngredientId");

                    b.ToTable("IngredientSubstitutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClosenessRank = 2,
                            DishImpact = "The dish will taste very similar but with a milder, less complex basil note.",
                            Explanation = "Thai basil is the closest substitute — it shares the same anise-like fragrance but is less peppery and slightly sweeter.",
                            OriginalIngredientId = 4,
                            SubstituteIngredientId = 5
                        },
                        new
                        {
                            Id = 2,
                            ClosenessRank = 3,
                            DishImpact = "The dish will taste noticeably different; fresher and sweeter, without the signature spicy edge.",
                            Explanation = "Italian basil is a last resort — it lacks the peppery heat of holy basil entirely.",
                            OriginalIngredientId = 4,
                            SubstituteIngredientId = 6
                        });
                });

            modelBuilder.Entity("CookingApp.Core.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FlavorTags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MainIngredientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Country");

                    b.HasIndex("MainIngredientName");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Main",
                            CookTimeMinutes = 40,
                            Country = "India",
                            CreatedAt = new DateTime(2026, 4, 4, 13, 53, 6, 917, DateTimeKind.Utc).AddTicks(905),
                            Description = "A hearty North Indian chickpea curry fragrant with whole spices and tangy tomatoes.",
                            FlavorTags = "spicy,savory,tangy",
                            ImageUrl = "",
                            Instructions = "1. Soak chickpeas overnight and boil until tender.\n2. Fry onion until golden, add garlic and ginger paste.\n3. Add tomatoes and cook to a thick masala.\n4. Stir in cumin, coriander, garam masala and chickpeas.\n5. Simmer 20 minutes. Serve with rice or bhatura.",
                            MainIngredientName = "Chickpeas",
                            Name = "Channa Masala",
                            PrepTimeMinutes = 20,
                            Servings = 4
                        },
                        new
                        {
                            Id = 2,
                            Category = "Main",
                            CookTimeMinutes = 10,
                            Country = "Austria",
                            CreatedAt = new DateTime(2026, 4, 4, 13, 53, 6, 917, DateTimeKind.Utc).AddTicks(913),
                            Description = "Crispy golden Austrian-style breaded chicken breast.",
                            FlavorTags = "savory,crispy",
                            ImageUrl = "",
                            Instructions = "1. Pound chicken breast to even thickness.\n2. Season with salt and pepper.\n3. Coat in flour, dip in beaten egg, then breadcrumbs.\n4. Fry in hot oil 3-4 min per side until golden.\n5. Drain and serve with lemon.",
                            MainIngredientName = "Chicken Breast",
                            Name = "Chicken Schnitzel",
                            PrepTimeMinutes = 15,
                            Servings = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Breakfast",
                            CookTimeMinutes = 15,
                            Country = "United States",
                            CreatedAt = new DateTime(2026, 4, 4, 13, 53, 6, 917, DateTimeKind.Utc).AddTicks(915),
                            Description = "Classic American crispy shredded potato patties.",
                            FlavorTags = "savory,crispy",
                            ImageUrl = "",
                            Instructions = "1. Grate potatoes and squeeze out all moisture.\n2. Season with salt and pepper.\n3. Press into patties and fry in butter on medium-high.\n4. Cook 4-5 min per side until deep golden brown.",
                            MainIngredientName = "Potato",
                            Name = "Hash Browns",
                            PrepTimeMinutes = 10,
                            Servings = 2
                        },
                        new
                        {
                            Id = 4,
                            Category = "Main",
                            CookTimeMinutes = 8,
                            Country = "Thailand",
                            CreatedAt = new DateTime(2026, 4, 4, 13, 53, 6, 917, DateTimeKind.Utc).AddTicks(917),
                            Description = "Thai stir-fried minced chicken with holy basil — Thailand's most beloved street food.",
                            FlavorTags = "spicy,savory,aromatic",
                            ImageUrl = "",
                            Instructions = "1. Stir-fry garlic and chili in oil.\n2. Add minced chicken, cook through.\n3. Season with fish sauce, oyster sauce, soy sauce.\n4. Toss in holy basil off heat.\n5. Serve over jasmine rice with a fried egg.",
                            MainIngredientName = "Chicken Breast",
                            Name = "Pad Kra Pao",
                            PrepTimeMinutes = 10,
                            Servings = 2
                        });
                });

            modelBuilder.Entity("CookingApp.Core.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            IsOptional = false,
                            Quantity = "400g",
                            SortOrder = 1
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 9,
                            IsOptional = false,
                            Quantity = "2 large",
                            SortOrder = 2
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 10,
                            IsOptional = false,
                            Quantity = "1 large",
                            SortOrder = 3
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 11,
                            IsOptional = false,
                            Quantity = "4 cloves",
                            SortOrder = 4
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 12,
                            IsOptional = false,
                            Quantity = "1 inch",
                            SortOrder = 5
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 13,
                            IsOptional = false,
                            Quantity = "1 tsp",
                            SortOrder = 6
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 14,
                            IsOptional = false,
                            Quantity = "2 tsp",
                            SortOrder = 7
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 15,
                            IsOptional = false,
                            Quantity = "1 tsp",
                            SortOrder = 8
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 1,
                            IsOptional = false,
                            Quantity = "2 pieces",
                            SortOrder = 1
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 7,
                            IsOptional = false,
                            Quantity = "2",
                            SortOrder = 2
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 8,
                            IsOptional = false,
                            Quantity = "1 cup",
                            SortOrder = 3
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 20,
                            IsOptional = false,
                            Quantity = "½ cup",
                            SortOrder = 4
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 3,
                            IsOptional = false,
                            Quantity = "3 large",
                            SortOrder = 1
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 1,
                            IsOptional = false,
                            Quantity = "300g minced",
                            SortOrder = 1
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 4,
                            IsOptional = false,
                            Quantity = "1 cup",
                            SortOrder = 2
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 11,
                            IsOptional = false,
                            Quantity = "5 cloves",
                            SortOrder = 3
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 19,
                            IsOptional = false,
                            Quantity = "3",
                            SortOrder = 4
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 16,
                            IsOptional = false,
                            Quantity = "1 tbsp",
                            SortOrder = 5
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 17,
                            IsOptional = false,
                            Quantity = "1 tbsp",
                            SortOrder = 6
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 18,
                            IsOptional = false,
                            Quantity = "½ tbsp",
                            SortOrder = 7
                        });
                });

            modelBuilder.Entity("CookingApp.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CookingApp.Core.Models.UserDislikedIngredient", b =>
                {
                    b.Property<int>("UserPreferencesId")
                        .HasColumnType("integer");

                    b.Property<int>("IngredientId")
                        .HasColumnType("integer");

                    b.HasKey("UserPreferencesId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("UserDislikedIngredients");
                });

            modelBuilder.Entity("CookingApp.Core.Models.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DislikedFlavors")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("CookingApp.Core.Models.UserSavedRecipe", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RecipeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserSavedRecipes");
                });

            modelBuilder.Entity("CookingApp.Core.Models.IngredientSubstitute", b =>
                {
                    b.HasOne("CookingApp.Core.Models.Ingredient", "OriginalIngredient")
                        .WithMany("Substitutes")
                        .HasForeignKey("OriginalIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CookingApp.Core.Models.Ingredient", "SubstituteIngredient")
                        .WithMany()
                        .HasForeignKey("SubstituteIngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OriginalIngredient");

                    b.Navigation("SubstituteIngredient");
                });

            modelBuilder.Entity("CookingApp.Core.Models.RecipeIngredient", b =>
                {
                    b.HasOne("CookingApp.Core.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookingApp.Core.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookingApp.Core.Models.UserDislikedIngredient", b =>
                {
                    b.HasOne("CookingApp.Core.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookingApp.Core.Models.UserPreferences", "UserPreferences")
                        .WithMany("DislikedIngredients")
                        .HasForeignKey("UserPreferencesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("UserPreferences");
                });

            modelBuilder.Entity("CookingApp.Core.Models.UserPreferences", b =>
                {
                    b.HasOne("CookingApp.Core.Models.User", "User")
                        .WithOne("Preferences")
                        .HasForeignKey("CookingApp.Core.Models.UserPreferences", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookingApp.Core.Models.UserSavedRecipe", b =>
                {
                    b.HasOne("CookingApp.Core.Models.Recipe", "Recipe")
                        .WithMany("SavedByUsers")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookingApp.Core.Models.User", "User")
                        .WithMany("SavedRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookingApp.Core.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("Substitutes");
                });

            modelBuilder.Entity("CookingApp.Core.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");

                    b.Navigation("SavedByUsers");
                });

            modelBuilder.Entity("CookingApp.Core.Models.User", b =>
                {
                    b.Navigation("Preferences");

                    b.Navigation("SavedRecipes");
                });

            modelBuilder.Entity("CookingApp.Core.Models.UserPreferences", b =>
                {
                    b.Navigation("DislikedIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
